In [1]:
import numpy as np

 missing cuda symbols while dynamic loading
 cuFile initialization failed


In [12]:
def extract_results_pp(pp_config):
    np.set_printoptions(precision=20)
    fold_results = []
    if pp_config in ['pp1', 'pp2']:
        for rate in [0.9, 0.75, 0.25, 0.1]:
            fold_0 = np.load(f'/home/nalvarez/experiments_Swin-UNETR/post-processing/results/{pp_config}/rate_{rate}/fold_0.npy')
            fold_1 = np.load(f'/home/nalvarez/experiments_Swin-UNETR/post-processing/results/{pp_config}/rate_{rate}/fold_1.npy')
            fold_2 = np.load(f'/home/nalvarez/experiments_Swin-UNETR/post-processing/results/{pp_config}/rate_{rate}/fold_2.npy')
            fold_3 = np.load(f'/home/nalvarez/experiments_Swin-UNETR/post-processing/results/{pp_config}/rate_{rate}/fold_3.npy')
            fold_4 = np.load(f'/home/nalvarez/experiments_Swin-UNETR/post-processing/results/{pp_config}/rate_{rate}/fold_4.npy')

            mean_f0 = np.nanmean(fold_0, axis=0)
            mean_f1 = np.nanmean(fold_1, axis=0)
            mean_f2 = np.nanmean(fold_2, axis=0)
            mean_f3 = np.nanmean(fold_3, axis=0)
            mean_f4 = np.nanmean(fold_4, axis=0)

            folds = np.concatenate(([mean_f0], [mean_f1], [mean_f2], [mean_f3], [mean_f4]))
            folds = np.mean(folds, axis=0)
            fold_results.append(folds)
        # Stack arrays along a new dimension to create a (3, 100, 12) array for comparison
        stacked_arrays = np.stack(fold_results)

        # Find the maximum value for each of the 12 columns across all arrays
        column_max_values = stacked_arrays.max(axis=0)

        # Identify the index of the array with the best (maximum) value for each of the 12 columns
        best_array_indices = np.argmax(stacked_arrays, axis=0)

        # Create a list of tuples (array index, max value) for each column
        rate_names = ['0.9', '0.75', '0.25', '0.1']
        result_tuples = [(rate_names[int(best_array_indices[i])], column_max_values[i]) for i in range(best_array_indices.shape[0])]

        return result_tuples
    
    else:
        fold_0 = np.load(f'/home/nalvarez/experiments_Swin-UNETR/post-processing/results/{pp_config}/fold_0.npy')
        fold_1 = np.load(f'/home/nalvarez/experiments_Swin-UNETR/post-processing/results/{pp_config}/fold_1.npy')
        fold_2 = np.load(f'/home/nalvarez/experiments_Swin-UNETR/post-processing/results/{pp_config}/fold_2.npy')
        fold_3 = np.load(f'/home/nalvarez/experiments_Swin-UNETR/post-processing/results/{pp_config}/fold_3.npy')
        fold_4 = np.load(f'/home/nalvarez/experiments_Swin-UNETR/post-processing/results/{pp_config}/fold_4.npy')

        mean_f0 = np.nanmean(fold_0, axis=0)
        mean_f1 = np.nanmean(fold_1, axis=0)
        mean_f2 = np.nanmean(fold_2, axis=0)
        mean_f3 = np.nanmean(fold_3, axis=0)
        mean_f4 = np.nanmean(fold_4, axis=0)

        folds = np.concatenate(([mean_f0], [mean_f1], [mean_f2], [mean_f3], [mean_f4]))
        folds = np.mean(folds, axis=0)

        return folds

In [3]:
def compare_results(pp_res_list):
    # Stack arrays along a new dimension to create a (3, 100, 12) array for comparison
    stacked_arrays = np.stack(pp_res_list)

    # Find the maximum value for each of the 12 columns across all arrays
    column_max_values = stacked_arrays.max(axis=0)

    # Identify the index of the array with the best (maximum) value for each of the 12 columns
    best_array_indices = np.argmax(stacked_arrays, axis=0)

    # Create a list of tuples (array index, max value) for each column
    rate_names = ['no pp', 'pp1', 'pp2', 'pp3', 'pp4']
    result_tuples = [(rate_names[int(best_array_indices[i])], column_max_values[i]) for i in range(best_array_indices.shape[0])]

    return result_tuples

In [49]:
no_pp = extract_results_pp('no_pp')
pp1 = extract_results_pp('pp1')
pp1 = [x[1] for x in pp1]
pp2 = extract_results_pp('pp2')
pp2 = [x[1] for x in pp2]
pp3 = extract_results_pp('pp3')
pp4 = extract_results_pp('pp4')

In [46]:
print(no_pp)
print(np.mean(no_pp, axis=0))

[0.9608854585795947 0.9523601632408664 0.9472658106397883
 0.826098718463375  0.8327974204334339 0.9764277073039554
 0.9204760986766711 0.9487521221843365 0.9026456960855533
 0.860854749363128  0.787679463935174  0.7850235718091965]
0.8917722483929227


In [47]:
pp1

[('0.9', 0.9606436098252733),
 ('0.9', 0.9534711925943109),
 ('0.9', 0.9508893757317558),
 ('0.9', 0.826098718463375),
 ('0.9', 0.8328319383144397),
 ('0.75', 0.9771779810891752),
 ('0.9', 0.9205008034732242),
 ('0.9', 0.949279788145771),
 ('0.25', 0.9028751460232233),
 ('0.1', 0.8610854114232378),
 ('0.1', 0.7876390238525265),
 ('0.9', 0.7852114560855445)]

In [48]:
pp2

[('0.9', 0.9611286459449844),
 ('0.9', 0.9534711925943109),
 ('0.9', 0.9508893757317558),
 ('0.9', 0.826098718463375),
 ('0.9', 0.8328319383144397),
 ('0.9', 0.9771779810891752),
 ('0.9', 0.9205008034732242),
 ('0.9', 0.949279788145771),
 ('0.25', 0.9028751460232233),
 ('0.25', 0.8610996804264929),
 ('0.1', 0.7876390238525265),
 ('0.9', 0.785261539296713)]

In [50]:
results = compare_results([no_pp, pp1, pp2, pp3, pp4])

In [51]:
results

[('pp3', 0.9622761459200897),
 ('pp3', 0.954037557487581),
 ('pp3', 0.9514326379143003),
 ('pp3', 0.8270579757082744),
 ('pp1', 0.8328319383144397),
 ('pp1', 0.9771779810891752),
 ('pp3', 0.9214943070673899),
 ('pp1', 0.949279788145771),
 ('pp1', 0.9028751460232233),
 ('pp2', 0.8610996804264929),
 ('no pp', 0.787679463935174),
 ('pp3', 0.7871742995817308)]

In [52]:
(np.array([x[1] for x in results]) * 100).round(3)

array([96.228, 95.404, 95.143, 82.706, 83.283, 97.718, 92.149, 94.928,
       90.288, 86.11 , 78.768, 78.717])

In [64]:
np.mean((np.array([x[1] for x in results]) * 100)).round(3)

89.287

In [62]:
np.array([x[1] for x in results])

array([0.9622761459200897, 0.954037557487581 , 0.9514326379143003,
       0.8270579757082744, 0.8328319383144397, 0.9771779810891752,
       0.9214943070673899, 0.949279788145771 , 0.9028751460232233,
       0.8610996804264929, 0.787679463935174 , 0.7871742995817308])

In [67]:
((np.array([x[1] for x in results]) * 100) - (no_pp * 100)).round(3)

array([0.139, 0.168, 0.417, 0.096, 0.003, 0.075, 0.102, 0.053, 0.023,
       0.024, 0.   , 0.215])