In [1]:
import json 
import numpy as np

In [2]:
swinunetr_cross = json.load(open("/experiments_Swin-UNETR/validation_dice_calculation/validation_results_per_fold/summary_cross_val.json"))

In [4]:
btcv_res = []
amos_res = []
totalseg_res = []
for case in swinunetr_cross['metric_per_case']:
    case_name = case['reference_file'].split('/')[-1].split('.')[0]
    if case_name.startswith('img'):
        dice_per_organ = []
        for key in case['metrics'].keys():
            dice_per_organ.append(case['metrics'][key])
        btcv_res.append(dice_per_organ)
    if case_name.startswith('amos'):
        dice_per_organ = []
        for key in case['metrics'].keys():
            dice_per_organ.append(case['metrics'][key])
        amos_res.append(dice_per_organ)
    if case_name.startswith('s'):
        dice_per_organ = []
        for key in case['metrics'].keys():
            dice_per_organ.append(case['metrics'][key])
        totalseg_res.append(dice_per_organ)

In [9]:
print(np.mean(btcv_res, axis=0).round(4)*100)
print(np.mean(btcv_res).round(4)*100)

[90.66 89.47 87.49 68.89 76.41 95.52 90.46 90.77 86.2  80.2  68.69 68.51]
82.77


In [10]:
print(np.mean(amos_res, axis=0).round(4)*100)
print(np.mean(amos_res).round(4)*100)

[95.57 94.76 94.34 83.   79.2  96.93 89.9  92.91 87.18 82.61 72.35 71.37]
86.68


In [11]:
print(np.mean(totalseg_res, axis=0).round(4)*100)
print(np.mean(totalseg_res).round(4)*100)

[96.89 96.05 95.59 83.38 86.77 98.32 93.73 96.62 92.8  89.06 84.17 84.43]
91.47999999999999
